# Generated by Django 4.2.5 on 2023-10-18 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('pricemin', models.IntegerField()),
                ('pricemax', models.IntegerField()),
                ('manzil', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('category5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viloyat5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.viloyat')),
            ],
        ),
    ]
