# Generated by Django 4.2.5 on 2023-10-18 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('manzil', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('img', models.ImageField(upload_to='apply/')),
                ('time', models.DateTimeField(auto_now=True)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.viloyat')),
            ],
        ),
    ]
