# Generated by Django 4.2.5 on 2023-10-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_apply_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='viloyat',
        ),
    ]
