# Generated by Django 4.2.5 on 2023-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_apply_job_viloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='counter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
