# Generated by Django 4.2.5 on 2023-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='messages/')),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
    ]
