# Generated by Django 4.2.5 on 2023-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
